CREATE TABLE AuditLog(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    LogDate DATE
);

--Trigger
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog(
        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        LogDate
    )
    VALUES(
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE
    );

END;
/

--Test
INSERT INTO Transactions(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES(
    3,
    1,
    SYSDATE,
    1000,
    'Deposit'
);

--Verify
SELECT * FROM AuditLog;